[book]
authors = ["ByteDance", "Rspack Rust Book Contributors"]
language = "en"
src = "src"
title = "Rspack Rust Book"

[output.html]
git-repository-url = "https://github.com/rspack-contrib/rspack-rust-book/tree/main"
edit-url-template = "https://github.com/rspack-contrib/rspack-rust-book/tree/main/{path}"
additional-css = ["res/mermaid-anti-flash.css"]
additional-js = ["res/mermaid-anti-flash.js", "res/mermaid.min.js", "res/mermaid-init.js"]

[output.linkcheck]
traverse-parent-directories = false
optional = true
follow-web-links = true

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
