name: github pages

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Setup mdBook mermaid
        run: |
          mkdir -p mdbook-mermaid
          curl -Lf https://github.com/badboy/mdbook-mermaid/releases/download/v0.15.0/mdbook-mermaid-v0.15.0-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook-mermaid
          echo "$(pwd)/mdbook-mermaid" >> $GITHUB_PATH

      - name: Build
        run: mdbook build

      - name: Test
        run: mdbook test

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/html
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
        # Only deploy on a push to main, not on a pull request.
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'rspack-contrib/rspack-rust-book'
